!define MUI_PAGE_CUSTOMFUNCTION_PRE SetupFinishPage
!define MUI_PAGE_CUSTOMFUNCTION_SHOW ShowFinishPage
!define MUI_PAGE_CUSTOMFUNCTION_LEAVE ValidateFinish
!define MUI_FINISHPAGE_TEXT_REBOOT "$(TEXT_REBOOT)"
!define MUI_FINISHPAGE_RUN ""
!define MUI_FINISHPAGE_RUN_TEXT $(RUN_LS)

!insertmacro MUI_PAGE_FINISH