!define MUI_PAGE_CUSTOMFUNCTION_PRE SetupFinishPage
;!define MUI_PAGE_CUSTOMFUNCTION_SHOW ShowFinishPage
;!define MUI_PAGE_CUSTOMFUNCTION_LEAVE ValidateFinish

!define MUI_FINISHPAGE_NOREBOOTSUPPORT
!define MUI_FINISHPAGE_NOAUTOCLOSE
!define MUI_FINISHPAGE_RUN
!define MUI_FINISHPAGE_RUN_TEXT $(RUN_LS)
!define MUI_FINISHPAGE_RUN_NOTCHECKED
!define MUI_FINISHPAGE_RUN_FUNCTION FinishRun

!insertmacro MUI_PAGE_FINISH