!ifndef PAGE_START_MENU
!define PAGE_START_MENU
	var ICONS_GROUP
	;!define MUI_STARTMENUPAGE_TEXT_TOP "$(TEXT_STARTMENUPAGE)"
	!define MUI_STARTMENUPAGE_DEFAULTFOLDER "${PRODUCT_NAME}"
	!define MUI_STARTMENUPAGE_REGISTRY_ROOT "${PRODUCT_UNINST_ROOT_KEY}"
	!define MUI_STARTMENUPAGE_REGISTRY_KEY "${PRODUCT_UNINST_KEY}"
	!define MUI_STARTMENUPAGE_REGISTRY_VALUENAME "${PRODUCT_STARTMENU_REGVAL}"
	!insertmacro MUI_PAGE_STARTMENU Application $ICONS_GROUP
!endif